
version: "3.9"

services:
  api:
    build: ./server
    container_name: mainclientgallery_api
    ports:
      - "3034:3034"
    volumes:
      - /mnt/apps/mainclientgallery:/app/data
      - /mnt/nextcloud/mainclientgalleryfiles:/app/storage
    environment:
      - MONGO_URL=mongodb://mongo:27017
      - DB_NAME=mainclientgallery
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:6
    container_name: mainclientgallery_mongo
    volumes:
      - /mnt/apps/mainclientgallery/mongodb:/data/db
    restart: unless-stopped
